#       ___  __   __   __
# |__| |__  |__) /  ' /  \ |\ |
# |  | |___ |  \ \__. \__/ | \|

# Настройки VK API
longpoll:
  # Токен доступа
  token: TOKEN
  # Версия
  version: 5.131
  # ID группы с ботом
  group_id: ID

# Настройки логирования
logging:
  # Запись логов в файл
  log_to_file: false

# Основные настройки
general:
  # Символы команд
  command_symbols: ['/', '!']
  # ID пользователей с доступом к боту
  users_ids:
    - ID1
    - ID2